attendance/urls.py
from django.urls import path
app_name='attendance'
from attendance import views
urlpatterns=[
    path('',views.attendance_form,name="attendance_form"),
    path('branch/',views.load_branch_details,name='ajax-load-branch'),
    path('subject/',views.load_subject_details,name='ajax-load-subject'),
    path('studentlist',views.studentlist,name='studentlist'),
    path('mark',views.mark),
    path('pastattendance',views.pastattendance),
    path('so',views.load_topics),

]

erp/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
#from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index),
	path('student/',include('student.urls')),
	path('teacher/',include('teacher.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teacher/urls.py
from django.urls import path,include
from . import views

app_name='teacher'

urlpatterns = [
    path('',views.index,name="index"),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('forget/',views.forget,name='forget'),
    path("subject/",views.subject,name="subject"),
    path('timetable/',views.timetable,name="timetable"),
    path('your-timetable/',views.teachertimetable,name="teacher_timetable"),
	path('attendance/',include('attendance.urls')),
    path('about/',views.about,name="about"),
    path('marks/',views.marks,name="marks"),
    path('marks-studentlist',views.studentlist),
    path('mark-marks',views.mark_marks),
    path('add-paper',views.addPaper),
    path('lds',views.lds),
    path('lds-form',views.ldsform),
    path('topics',views.load_topics), ##ajax from ldsform ##
    path('ajax/load-CO',views.load_objectives), ##ajax
    path('lab',views.lab),
]

attendance/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator,MaxValueValidator
from datetime import date
# Create your models here.
class mark_attendance(models.Model):
    student=models.ForeignKey("student.studentlogin",on_delete=models.CASCADE)
    session=models.IntegerField(validators=[MaxValueValidator(int(date.today().year))],default=int(date.today().year),editable=False)
    subject=models.ForeignKey("erp.subjects",on_delete=models.CASCADE)
    date=models.DateField(default=timezone.now)
    present=models.BooleanField("Present")
    lecture_number=models.IntegerField(validators=[MaxValueValidator(8),MinValueValidator(1)])
    semester=models.IntegerField(default=1,validators=[MaxValueValidator(8),MinValueValidator(1)],editable=False)
    teacher=models.ForeignKey("teacher.teacherlogin",on_delete=models.CASCADE)
    topics=models.JSONField(null=True,blank=True)
    def __str__(self):
        return str(self.student)+" : "+str(self.date)+" : "+str(self.lecture_number)
    class Meta:
        unique_together=[["student","date","lecture_number"]]
    
    attend_obj=models.Manager()

teacher/models.py
from django.db import models
from django.contrib.auth.models import Group
from django.core.validators import MinLengthValidator
from django.db.models.signals import post_save,post_delete

from django.contrib.auth.models import User

from erp.services import create_new_password
from erp.extra import MyLogger

logger=MyLogger(__name__).get_logger()

# Create your models here.
def createuser(**kwargs):
	if kwargs["created"] and isinstance(kwargs["instance"],teacherlogin):
		
		pwd=create_new_password(kwargs['instance'])

		fname=kwargs["instance"].name
		fname=fname.split()
		try:
			lname=fname[1]
		except:
			lname=''
		fname=fname[0]

		user = User.objects.create_user(username=kwargs["instance"].teacherid,email=kwargs["instance"].email,password=kwargs["instance"].pwd,first_name=fname,last_name=lname)
		try:
			user_group = Group.objects.get(name='teacher')
		except:
			user_group=Group.objects.create(name="teacher")
		user.groups.add(user_group)
		user.is_staff=True
		user.save()

	elif isinstance(kwargs["instance"],teacherlogin):
			logger.debug(f'Updating {kwargs["instance"].teacherid}')
			u = User.objects.get(username=kwargs["instance"].teacherid)
			if not u.check_password(kwargs["instance"].pwd):
				print(111111111111111111111111)
				u.set_password(kwargs["instance"].pwd)
				u.save()

def deleteuser(**kwargs):
	if isinstance(kwargs["instance"],teacherlogin):
		try:
			u=User.objects.get(username=kwargs["instance"].teacherid)
			u.delete()
		except Exception as e:
			logger.error(str(e))

class teacherlogin(models.Model):

	teacherid=models.CharField(max_length=20,primary_key=True)
	name=models.CharField(max_length=40)
	pwd=models.CharField(max_length=15,validators=[MinLengthValidator(8, 'the field must contain at least 8 characters')])
	blood_group=models.CharField(max_length=5)
	gender=models.CharField(choices=(('MALE','MALE'),("FEMALE","FEMALE"),("OTHERS","OTHERS")),max_length=50)
	address=models.CharField(max_length=50, blank=True, null=True)
	# isactive=models.IntegerField(null=True,blank=True)
	branch=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,null=True,blank=True)
	cc_of_branch=models.ForeignKey("branch.branch_detail",null=True,blank=True,default=None,on_delete=models.CASCADE,related_name="Class_Coordinator")
	email=models.EmailField(max_length=50)

	teach_mon_lec1=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_mon_l1',default=None,null=True,editable=False)
	teach_mon_lec2=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_mon_l2',default=None,null=True,editable=False)
	teach_mon_lec3=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_mon_l3',default=None,null=True,editable=False)
	teach_mon_lec4=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_mon_l4',default=None,null=True,editable=False)
	teach_mon_lec5=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_mon_l5',default=None,null=True,editable=False)
	teach_mon_lec6=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_mon_l6',default=None,null=True,editable=False)
	teach_mon_lec7=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_mon_l7',default=None,null=True,editable=False)
	teach_mon_lec8=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_mon_l8',default=None,null=True,editable=False)

	teach_tues_lec1=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_tues_l1',default=None,null=True,editable=False)
	teach_tues_lec2=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_tues_l2',default=None,null=True,editable=False)
	teach_tues_lec3=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_tues_l3',default=None,null=True,editable=False)
	teach_tues_lec4=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_tues_l4',default=None,null=True,editable=False)
	teach_tues_lec5=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_tues_l5',default=None,null=True,editable=False)
	teach_tues_lec6=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_tues_l6',default=None,null=True,editable=False)
	teach_tues_lec7=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_tues_l7',default=None,null=True,editable=False)
	teach_tues_lec8=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_tues_l8',default=None,null=True,editable=False)

	teach_wed_lec1=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_wed_l1',default=None,null=True,editable=False)
	teach_wed_lec2=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_wed_l2',default=None,null=True,editable=False)
	teach_wed_lec3=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_wed_l3',default=None,null=True,editable=False)
	teach_wed_lec4=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_wed_l4',default=None,null=True,editable=False)
	teach_wed_lec5=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_wed_l5',default=None,null=True,editable=False)
	teach_wed_lec6=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_wed_l6',default=None,null=True,editable=False)
	teach_wed_lec7=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_wed_l7',default=None,null=True,editable=False)
	teach_wed_lec8=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_wed_l8',default=None,null=True,editable=False)

	teach_thurs_lec1=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_thurs_l1',default=None,null=True,editable=False)
	teach_thurs_lec2=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_thurs_l2',default=None,null=True,editable=False)
	teach_thurs_lec3=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_thurs_l3',default=None,null=True,editable=False)
	teach_thurs_lec4=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_thurs_l4',default=None,null=True,editable=False)
	teach_thurs_lec5=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_thurs_l5',default=None,null=True,editable=False)
	teach_thurs_lec6=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_thurs_l6',default=None,null=True,editable=False)
	teach_thurs_lec7=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_thurs_l7',default=None,null=True,editable=False)
	teach_thurs_lec8=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_thurs_l8',default=None,null=True,editable=False)

	teach_fri_lec1=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_fri_l1',default=None,null=True,editable=False)
	teach_fri_lec2=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_fri_l2',default=None,null=True,editable=False)
	teach_fri_lec3=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_fri_l3',default=None,null=True,editable=False)
	teach_fri_lec4=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_fri_l4',default=None,null=True,editable=False)
	teach_fri_lec5=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_fri_l5',default=None,null=True,editable=False)
	teach_fri_lec6=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_fri_l6',default=None,null=True,editable=False)
	teach_fri_lec7=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_fri_l7',default=None,null=True,editable=False)
	teach_fri_lec8=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_fri_l8',default=None,null=True,editable=False)

	teach_sat_lec1=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_sat_l1',default=None,null=True,editable=False)
	teach_sat_lec2=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_sat_l2',default=None,null=True,editable=False)
	teach_sat_lec3=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_sat_l3',default=None,null=True,editable=False)
	teach_sat_lec4=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_sat_l4',default=None,null=True,editable=False)
	teach_sat_lec5=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_sat_l5',default=None,null=True,editable=False)
	teach_sat_lec6=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_sat_l6',default=None,null=True,editable=False)
	teach_sat_lec7=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_sat_l7',default=None,null=True,editable=False)
	teach_sat_lec8=models.ForeignKey("branch.branch_detail",on_delete=models.CASCADE,related_name='teach_sat_l8',default=None,null=True,editable=False)

	teach_obj = models.Manager()
	def __str__(self):
		return self.teacherid
	
	post_save.connect(createuser)
	post_delete.connect(deleteuser)

attendance/forms.py
from django import forms
from .models import mark_attendance
from erp.models import course,subjects
from branch.models import branch_detail
from datetime import datetime


class mark_attendance_form(forms.ModelForm):
    course=forms.ModelChoiceField(queryset=course.course_obj.all())
    batch=forms.IntegerField(max_value=int(datetime.now().year),min_value=int(datetime.now().year-4))
    branch=forms.ModelChoiceField(queryset=branch_detail.branch_obj.all())
    SECTION_CHOICES =(
    (None,'------'),
    ("A", "A"),
    ("B", "B"),
    ("C", "C"),
    ("D", "D"),
    )
    section=forms.ChoiceField(choices=SECTION_CHOICES)

    group_choices=(
        ("Both","Both"),
        ("Batch1","Batch-1"),
        ("Batch2","Batch-2")
    )
    group=forms.ChoiceField(choices=group_choices)

    class Meta:
        model=mark_attendance
        fields=('course','batch','branch','section','subject','group')

        widgets={
            'course':forms.Select(attrs={'id':'course','class':'form-control'}),
            'batch':forms.TextInput(attrs={'id':'batch','class':'form-control'}),
            'branch':forms.Select(attrs={'id':'branch','class':'form-control'}),
        }
    def __init__(self,*args,**kwargs):

        super().__init__(*args, **kwargs)
        self.fields['branch'].queryset=branch_detail.branch_obj.none()
        self.fields['subject'].queryset=subjects.sub_obj.none()
        

        

teacher/templates/about.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}

    <head>
        <title>About</title>
        <!-- Favicon icon -->
        <link rel="icon" type="image/png" sizes="16x16" href={% static "images/favicon.png" %}>
        <link rel="stylesheet" href={% static 'css/style.css' %}>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"> -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <style>
            .profile-pic {
                border-radius: 50%;
                height: 150px;
                width: 150px;
                background-size: cover;
                background-position: center;
                background-blend-mode: multiply;
                vertical-align: middle;
                text-align: center;
                color: transparent;
                transition: all .3s ease;
                text-decoration: none;
                cursor: pointer;
            }

            .profile-pic:hover {
                background-color: rgba(0, 0, 0, .5);
                z-index: 10000;
                color: #fff;
                transition: all .3s ease;
                text-decoration: none;
            }

            .profile-pic span {
                display: inline-block;
                padding-top: 4.5em;
                padding-bottom: 4.5em;
            }

            form input[type="file"] {
                display: none;
                cursor: pointer;
            }
		#my-dialog{
			background-color:rgb(189, 236, 255);
			margin-right: 1%;
			border-radius: 5%;
			padding: 23px;
			border: none;
			/* top: -8%; */
			color:rgb(5, 41, 56);
		}
		
        </style>
    </head>

    <body>
        <div id="main-wrapper">
            {%include "navbar.html" %}
            <div class="content-body">
                <!-- row -->
                <div class="container-fluid">

                    <div class="row">
                        <div class="col-xl-12 col-xxl-12 col-lg-12 col-md-12 col-sm-12">
                            <div class="card">
                                <div class="card-header">
                                    <h3 class="card-title">About</h3>
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-4" align="center"
                                            style="border-right: 5px solid #ccc; padding: 20px;">
                                            <form action="upload.php" method="post" enctype="multipart/form-data">
                                                <label for="fileToUpload">
                                                    <div class="profile-pic"
                                                        style="background-image: url('https://randomuser.me/api/portraits/med/men/65.jpg')">
                                                        <span><i class="fa fa-edit"></i></span>
                                                    </div>
                                                </label>
                                                <input type="File" name="fileToUpload" id="fileToUpload">
                                            </form>
                                            {{user.Name}} <br>
                                            {{user.email}}
                                        </div>
                                        <div class="col-md-4" align="left"
                                            style="border-right: 5px solid #ccc; padding: 20px;">
                                            <div class="col-md-12">
                                                <label class="labels">Mobile No :</label>
                                                {{user.mobile}}
                                            </div></br>
                                            <div class="col-md-12">
                                                <label class="labels">Personal Email ID :</label>
                                                {{user.email}}
                                            </div></br>
                                            <div class="col-md-12">
                                                <label class="labels">Blood_Group :</label>
                                                {{user.bloodGroup}}
                                            </div></br>
                                            <div class="col-md-12">
                                                <label class="labels">Gender :</label>
                                                {{user.gender}}
                                            </div></br>
                                            <div class="col-md-12">
                                                <label class="labels">Address :</label>
                                                {{user.permanentAddress}}
                                            </div></br>
                                        </div>
                                        <div class="col-md-4" style="padding: 30px;">

                                            <div class="d-flex justify-content-between align-items-center experience">
                                                <form method="post" action="/teacher/about">
                                                    {% csrf_token %}
                                                    <a href="#" role="button">
                                                        <span>Add achievements</span>

                                                        <button class="border px-3 p-1 add-experience" type="button" onclick="openDialog()">
                                                            <i class="fa fa-plus"></i>&nbsp;Achievements
                                                        </button>
                                                    </a>
                                                    <dialog id="my-dialog">
                                                        <div>
                                                            <button type="button" onclick="closeDialog()"
                                                                style="float: right; background-color:rgb(189, 236, 255); border: 0ch;margin-top: 0;cursor: pointer;">
                                                                <i class="material-icons" style="font-size:20px;color:red;">highlight_off</i>
                                                            </button>
                                                            <br>
                                                            You are adding a subject to your department.
                                                            <br>
                                                            <label for="issuingOrganization">Issuing Organization:</label>
                                                            <input type="text" name="issuingOrganization"/>
                                                            <label for="issuingYear">Issuing Year:</label>
                                                            <input type="text" name="issuingYear"/>
                                                            <button type="submit" class="smallbutton">Add</button>
                                                        </div>
                                                    </dialog>
                                                </form>
                                            </div>
                                            <br>

                                            <div class="col-md-12">
                                                <label class="labels">Additional Details</label>
                                                <input type="text" class="form-control" placeholder="additional details"
                                                    value="">
                                            </div>

                                        </div>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>


        <!--**********************************
Content body end
***********************************-->





        <!--**********************************
Main wrapper end
***********************************-->

        <!--**********************************
Scripts
***********************************-->
        <!-- --------------- for profile image change-------------------- -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <!-- For opening dialog box -->
        <script>
            function openDialog() {
                var dialog = document.getElementById('my-dialog');
                dialog.open = true;
            }

            function closeDialog() {
                var dialog = document.getElementById('my-dialog');
                dialog.open = false;
            }
        </script>

        <script>
            // Get the input element where the user selects the new image
            const input = document.getElementById("input-image");

            input.addEventListener("change", function () {
                // Get the selected image file
                const imageFile = input.files[0];

                // Create a new FormData object to store the image file
                const formData = new FormData();
                formData.append("image", imageFile);

                // Use jQuery AJAX to send the image file to the server
                $.ajax({
                    type: "POST",
                    url: "/update-image/",
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (response) {
                        console.log(response);
                        // handle the response from the server
                    },
                    error: function (error) {
                        console.log(error);
                        // handle any errors that occur
                    }
                });
            });

        </script>
        <!-- Required vendors -->
        <script src={% static "vendor/global/global.min.js" %}></script>
        <script src={% static "vendor/bootstrap-select/dist/js/bootstrap-select.min.js" %}></script>
        <script src={% static "js/custom.min.js" %}></script>
        <script src={% static "js/dlabnav-init.js" %}></script>

        <!-- Chart sparkline plugin files -->
        <script src={% static "vendor/jquery-sparkline/jquery.sparkline.min.js" %}></script>
        <script src={% static "js/plugins-init/sparkline-init.js" %}></script>

        <!-- Chart Morris plugin files -->
        <script src={% static "vendor/raphael/raphael.min.js" %}></script>
        <script src={% static "vendor/morris/morris.min.js" %}></script>

        <!-- Init file -->
        <script src={% static "js/plugins-init/widgets-script-init.js" %}></script>

        <!-- Demo scripts -->
        <script src={% static "js/dashboard/dashboard.js" %}></script>

        <!-- Summernote -->
        <script src={% static "vendor/summernote/js/summernote.min.js" %}></script>
        <!-- Summernote init -->
        <script src={% static "js/plugins-init/summernote-init.js" %}></script>

        <!-- Svganimation scripts -->
        <script src={% static "vendor/svganimation/vivus.min.js" %}></script>
        <script src={% static "vendor/svganimation/svg.animation.js" %}></script>
        <!--script src={% static "js/styleSwitcher.js"></script-->
        <!--
to import settings change name of settings.js to sytleSwitcher.js
-->
    </body>

</html>

teacher/templates/load_topics.html
<!-- <option value="">---------</option> -->
{% for topic in topics_list %}
<option value="{{topic}}">{{topic|capfirst}}</option>
{% endfor %}

teacher/templates/marks.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
	<head>
		<title>Marks</title>
		<!-- Favicon icon -->
		<link rel="icon" type="image/png" sizes="16x16" href={% static "images/favicon.png" %}>
		<link rel="stylesheet" href={% static 'css/style.css' %}>
		<link rel="stylesheet" href={% static "css/skin-3.css" %}>
		<link rel="stylesheet" href={% static 'css/button.css' %}>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
		<!-- <script src="{% static 'js/markattendance.js' %}"></script> -->
		<link rel="stylesheet" href={% static "css/style2.css" %}>
		<style type="text/css">
			select{
				margin-bottom: 20px;
			}
			#id_batch{
				margin-bottom: 20px;
				width: 70px;
				height:23px;
			}
			.gray_button {
			border: none;
			padding: 6px 10px;
			text-align: center;
			display: inline-block;
			font-size: 15px;
			cursor: pointer;
			background-color: #e7e7e7; 
			color: black;
			float:right;
			border-radius: 20px;
			margin: 0 2px;
			}
			label{
				float:center;
			}
		</style>
	</head>

	<body>
		<div id="main-wrapper">
			{%include "navbar.html" %}
			<div class="content-body">
				<!-- row -->
				<div class="container-fluid">
					<div class="row">
						<div class="col-xl-12 col-xxl-12 col-lg-12 col-md-12 col-sm-12">
							<div class="card" >
								<div class="card-title">
									<b>{% block title %}Marks{% endblock %}</b>
									<a href="/teacher/mark-records"><button class="gray_button">Previous</button></a>
									<a href="/teacher/add-paper"><button class="gray_button">Add Paper+</button></a>

								</div><hr>
								<div class="card-body">
								{% block content %}
								<form action="/teacher/marks-studentlist" id="marks_form" method="POST">
									{% csrf_token %}
									{{form.as_ul}}
									<label>Exam-type:</label>
									<select name="exam-type" required !important>
										<option value="">--------</option>
										<option value="ST1">ST-1</option>
										<option value="ST2">ST-2</option>
										<option value="reST">re-ST</option>
										<option value="PUE">PUE</option>
										<option value="rePUE">re-PUE</option>
									</select>
									<br>
									<button type="submit" class="buttondesign">Mark</button>
								</form>
								</div>
								
								{% endblock %}
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--**********************************
	Content body end
	***********************************-->




		</div>
		<!--**********************************
	Main wrapper end
	***********************************-->
		<script>
			$(document).ready(function(){
			$("#id_batch").change(function () {
				var batch = $(this).val();
				var course=document.getElementById("id_course").value;
				$.ajax({                                          // initialize an AJAX request
					url: "/teacher/attendance/branch",                                    // set the url of the request (= ajax/load-department-details/ )
					data: { 'course': course,
							'batch':batch
				 		  },        // add the course  to the GET parameters
					success: function (data) {  
						$("#id_branch").html(data); 
					}
				});
			});

			$("#id_section").change(function () {
				const section = $(this).val();
				const branch=document.getElementById("id_branch").value;
				const batch=document.getElementById("id_batch").value;
				$.ajax({
					url: "/teacher/attendance/subject",
					data: {'branch': branch,
							'section':section,
							'batch':batch
					},
					success: function (data) {
						$("#id_subject").html(data);
					}
				});
			});
		});
		</script>
		<!--**********************************
	Scripts
	***********************************-->
		<!-- Required vendors -->
		<script src={% static "vendor/global/global.min.js"%}></script>
		<!-- <script src={% static "vendor/bootstrap-select/dist/js/bootstrap-select.min.js"%}></script> -->
		<script src={% static "js/custom.min.js"%}></script>
		<script src={% static "js/dlabnav-init.js"%}></script>

		<!-- Chart sparkline plugin files -->
		<script src={% static "vendor/jquery-sparkline/jquery.sparkline.min.js"%}></script>
		<script src={% static "js/plugins-init/sparkline-init.js"%}></script>

		<!-- Chart Morris plugin files -->
		<script src={% static "vendor/raphael/raphael.min.js"%}></script>
		<script src={% static "vendor/morris/morris.min.js"%}></script>

		<!-- Init file -->
		<script src={% static "js/plugins-init/widgets-script-init.js"%}></script>

		<!-- Demo scripts -->
		<script src={% static "js/dashboard/dashboard.js"%}></script>

		<!-- Summernote -->
		<script src={% static "vendor/summernote/js/summernote.min.js"%}></script>
		<!-- Summernote init -->
		<script src={% static "js/plugins-init/summernote-init.js"%}></script>

		<!-- Svganimation scripts -->
		<script src={% static "vendor/svganimation/vivus.min.js"%}></script>
		<script src={% static "vendor/svganimation/svg.animation.js"%}></script>
		<!--script src={% static "js/styleSwitcher.js"></script-->
		<!--
	to import settings change name of settings.js to sytleSwitcher.js
	-->
	</body>

</html>